version: '3.8'

services:
  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=notsecurepassword

  bitcoin-regtest:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin-regtest
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - type: bind
        source: ./volumes/bitcoin
        target: /home/bitcoin/.bitcoin
      - type: bind
        source: ./bitcoin.conf
        target: /home/bitcoin/.bitcoin/bitcoin.conf
    command:
      - bitcoind
      - -printtoconsole
      - -conf=/home/bitcoin/.bitcoin/bitcoin.conf

volumes:
  postgres:
  bitcoin: