version: '3.8'

services:
  bitcoind:
    image: "lightninglabs/bitcoin-core:25"
    command:
        - -regtest
        - -server
        - -rpcbind=0.0.0.0
        - -rpcallowip=0.0.0.0/0
        - -rpcuser=rpcuser
        - -rpcpassword=rpcpassword
        - -fallbackfee=0.0002
        - -txindex
    ports:
        - "18443:18443"

  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=notsecurepassword

volumes:
  postgres:
  bitcoin:
